# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kanna_02' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kanna', '~> 5.0.0'

  # Pods for Kanna_02

  target 'Kanna_02Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Kanna_02UITests' do
    # Pods for testing
  end

end
