# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CovidMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kanna', '~> 5.0.0'

  # Pods for CovidMap

  target 'CovidMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CovidMapUITests' do
    # Pods for testing
  end

end
